@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Patient *--> "1" UniqueVisitList

UniqueVisitList -down->"*" Visit

Visit *--> "1"Condition
Visit *--> "1"Severity
Visit *--> "1"DateOfVisit
@enduml
