@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":InputParser" as ip LOGIC_COLOR
Participant ":EditCommandParser" as ecp LOGIC_COLOR
Participant "command:EditCommand" as ec LOGIC_COLOR

[-> logic : execute
activate logic
logic -> ip ++: parseCommand(commandText)
create ecp
ip -> ecp
ip -> ecp ++: parse(arguments)
create ec
ecp -> ec ++: index, editPatientDescriptor
ec --> ecp --
ecp --> ip --: command
ip --> logic --: command

@enduml
