@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "PatientList Storage" #F4F6F6{
Class "<<interface>>\nPatientListStorage" as PatientListStorage
Class JsonPatientListStorage
Class JsonSerializablePatientList
Class JsonAdaptedPatient
Class JsonAdaptedVisit
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage

StorageManager -up-> "1" PatientListStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> PatientListStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonPatientListStorage .up.|> PatientListStorage

JsonPatientListStorage ..> JsonSerializablePatientList
JsonSerializablePatientList --> "*" JsonAdaptedPatient
JsonAdaptedPatient --> "*" JsonAdaptedVisit

@enduml
